# -*- mode: ruby -*-
# vi: set ft=ruby :

$script_installChef12 = <<SCRIPT
echo "Install of Chef server started..."
echo "Setting up hostname..."
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
mv /etc/hosts /etc/hosts.old
touch /etc/hosts
echo "172.16.1.5 chef-server" >> /etc/hosts
echo "127.0.0.1 chefServer" >> /etc/hosts
cd /opt/
echo "Downloading chef from repo..."
wget -nv -O /opt/chef-server-core_12.3.0-1_amd64.deb https://web-dl.packagecloud.io/chef/stable/packages/ubuntu/trusty/chef-server-core_12.3.0-1_amd64.deb
echo "Starting the installation onf chef-server-core..."
dpkg -i chef-server*
echo "Running the reconfigure command..."
chef-server-ctl reconfigure
echo "Making account and organization ..."
mkdir -p /opt/chef-server
sudo chef-server-ctl user-create --filename /opt/chef-server/vagrant.pem vagrant Vlad ENDAVA vlad.turbuleasa@endava.com vagrant
sudo chef-server-ctl org-create ssh DevOps --association_user vagrant --filename /opt/chef-server/ssh.pem
chef-server-ctl status
chef-server-ctl test
echo "Install of Chef server Done..."
SCRIPT

Vagrant.configure("2") do |config|
  
	config.vm.define "chefServer" do |chefServer|
     chefServer.vm.box = "ubuntu/trusty64"
     chefServer.vm.hostname = "chefServer"
     chefServer.vm.synced_folder ".", "/vagrant", type: "virtualbox", disabled: true
     chefServer.vm.provision :shell, :inline => $script_installChef12
     chefServer.vm.network "private_network", ip: "172.16.1.5", virtualbox__intnet: true
     chefServer.vm.network "forwarded_port", guest: 22, host: 5022, id: "ssh", auto_correct: true
     chefServer.vm.provider "virtualbox" do |vm|
      vm.name = "Chef-server-12"
			vm.customize [
							'modifyvm', :id,
							'--memory', '1536'
							
						]
		end
  end

end