## YAML Template.
---
  - name: Setting up nginx repository
    copy:
      dest: /etc/yum.repos.d/nginx.repo
      content: |
        [nginx]
        name=nginx repo
        baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
        gpgcheck=0
        enabled=1
    sudo: yes

  - name: Install nginx package
    yum: name=nginx state=present
    sudo: yes

  - name: Starting nginx service
    service: name=nginx state=started
    sudo: yes
